name: Build

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [submodule-update]

env:
  NODE_VERSION: "20.7" # Define the Node.js version here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build-github
          npm run node-modules-front
          npm run build-tailwind

    outputs:
      build-dir: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository (again, in case it's needed)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ${{ needs.build.outputs.build-dir }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_branch: gh-pages
