FROM nginx:alpine

LABEL org.opencontainers.image.source="https://github.com/do-it-ecm/do-it"
LABEL org.opencontainers.image.title="Do-It"
LABEL org.opencontainers.image.vendor="Do-It"
LABEL org.opencontainers.image.authors="BoxBoxJason"
LABEL org.opencontainers.image.description="Deploy the Do-It static website and serve it with nginx. Use the auto synchronizer to keep the website up to date."

WORKDIR /opt/do-it/

RUN apk update && \
    apk upgrade && \
    apk add --no-cache git python3 && \
    rm -rf /var/cache/apk/* && \
    rm -f /etc/nginx/http.d/default.conf && \
    echo "#!/bin/sh" > /etc/periodic/15min/synchronizer && \
    echo "/opt/do-it/jobs/synchronizer.sh" >> /etc/periodic/15min/synchronizer && \
    echo "#!/bin/sh" > /etc/periodic/daily/update && \
    echo "apk update; apk upgrade" >> /etc/periodic/daily/update && \
    chmod 750 /etc/periodic/15min/synchronizer /etc/periodic/daily/update && \
    adduser -D -u 1000 do-it && \
    chown -R root:do-it /opt/do-it/ && \
    chmod -R g+rwx /opt/do-it/

COPY --chown=root:do-it --chmod=750 ./entrypoint.sh /entrypoint.sh
COPY --chown=root:do-it --chmod=640 ./nginx.conf /etc/nginx/nginx.conf
COPY --chown=root:do-it --chmod=750 ./synchronizer.sh /opt/do-it/jobs/synchronizer.sh
COPY --chown=root:do-it --chmod=750 ./server.py /opt/do-it/jobs/server.py

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
